name: CI-CD1
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST1 }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu/Project-BE
            git config --global --add safe.directory /home/ubuntu/Project-BE
            sudo git pull
            sudo npm update
            sudo npm install
            sudo pm2 reload all
